// src/components/Main/Navigation/Navigation.tsx
import { createComponent } from '@vue/composition-api'
import NavigationContent from '@/components/Main/Navigation/NavigationContent'
import NavigationSelector from '@/components/Main/Navigation/NavigationSelector'
import styled from 'vue-styled-components'
import theme from '@/lib/theme'

export default createComponent({
  name: 'Navigation',
  setup() {
    return () => (
      <Wrapper>
        <NavigationSelector />
        <NavigationContent />
      </Wrapper>
    )
  }
})

const Wrapper = styled.div`
  width: 320px;
  flex-shrink: 0;
  height: 100vh;
  background: ${theme.background.secondary};
  overflow: scroll;
`

// src/components/Main/Navigation/Navigation.vue
<template>
  <div :class="$style.container" :style="navigationStyle">
    <NavigationSelector />
    <NavigationContent />
  </div>
</template>

<script lang="ts">
import { defineComponent, computed } from '@vue/composition-api'
import NavigationContent from '@/components/Main/Navigation/NavigationContent.vue'
import NavigationSelector from '@/components/Main/Navigation/NavigationSelector.vue'
import store from '@/store'

export default defineComponent({
  name: 'Navigation',
  components: { NavigationContent, NavigationSelector },
  setup() {
    const navigationStyle = computed(() => ({
      background: store.state.app.theme.background.secondary,
      color: store.state.app.theme.ui.primary
    }))
    return { navigationStyle }
  }
})
</script>

<style lang="scss" module>
.container {
  width: 100%;
  height: 100%;
}
</style>
